language: python
python:
- '2.7'
deploy:
- provider: pypi
  distributions: sdist
  server: https://testpypi.python.org/pypi
  user: rdrazny
  password:
    secure: orE1JYvuWqn7oZ2sVzRtgkLeR82KmPxRuJ9bnq4ny80uZ63F+OfhN8s5P2tpDz5UsjBJrropqmwg8fwg0z7RVZv/6H4y9D+CbKhTka5eONeItD/de5yWIdyRVCIBmpDDKhshlM/aYcy6MyY9WyYSfY+Nn2rgZOBqkMoCZdZmfuSbUML8PmfiGQ7aOo7YONCKI1CUVHrhvi3xXCETGV/tuT8oTivAwWXkME1jqqHAH5kJ95jzxxt4fat/5zQrpMmSyGtIYyBUrWmcvln/Skcpyax0wO83bBUw4dwjq4d+yoAyMLyUF2YqZo4wJvDya0/KBbivMBX2B5wsLp4WXXXvwymMGr6ct6GZNFlkprtM/ozmtqeOBbJGiqvy43vmw+RpyPDKd2bWj8SSa3UlXAUoN0yRzPpTX+z7DT2X9VUso7TKw2Qsv2zwBb6HR21ZfNALDAh6SD/xFTF8FZ57onxwyIA5HRd/T+KrLSSQy3ipajoxZNbhq8TaFvmGase9MxwybGwzL15ikx1r76LVO+ZaSfoRDXXJJQUy2lM4bNsHG8YJ7hK2Hjzbq56MuWxw91xHGc802X4251KM032FPP3GepVAhpLVbMmWOQkeaT42z3cZxTVSm1rzKqXVWJ7cN6PBahlfXPdr2yJsZK0iLfd6oX4X/7vcAw8QV181HFZIRbo=
  on:
    branch: master
    tags: false
    condition: $TRAVIS_PYTHON_VERSION = "2.7"